import {ButtonHTMLAttributes, PropsWithChildren, InputHTMLAttributes} from 'react';
import {cn} from '@/lib/utils';

export function Button({className,variant='default',...props}:{variant?:'default'|'ghost'|'danger'|'outline'}&ButtonHTMLAttributes<HTMLButtonElement>){return <button className={cn('inline-flex items-center justify-center rounded-xl px-4 py-2 text-sm font-bold transition active:scale-[.98] disabled:opacity-50',variant==='default'&&'bg-[rgb(var(--accent))] text-white hover:opacity-90',variant==='ghost'&&'hover:bg-slate-500/10',variant==='danger'&&'bg-red-600 text-white hover:bg-red-700',variant==='outline'&&'border bg-transparent hover:bg-slate-500/10',className)} {...props}/>}
export function Input({className,...props}:InputHTMLAttributes<HTMLInputElement>){return <input className={cn('w-full rounded-xl border bg-[rgb(var(--panel))] px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-[rgb(var(--accent)/.25)]',className)} {...props}/>}
export function Card({children,className}:{children:React.ReactNode;className?:string}){return <div className={cn('rounded-2xl border bg-[rgb(var(--panel))] shadow-panel',className)}>{children}</div>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'red'|'green'|'blue'|'amber'}){const c={neutral:'bg-slate-500/10 text-slate-600 dark:text-slate-300',red:'bg-red-500/10 text-red-700 dark:text-red-300',green:'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300',blue:'bg-blue-500/10 text-blue-700 dark:text-blue-300',amber:'bg-amber-500/10 text-amber-700 dark:text-amber-300'}[tone];return <span className={cn('rounded-full px-2.5 py-1 text-xs font-bold',c)}>{children}</span>}
export function StatCard({label,value,caption}:{label:string;value:string|number;caption?:string}){return <Card className="p-5"><div className="text-xs font-semibold text-slate-500">{label}</div><div className="mt-2 text-3xl font-black tracking-tight">{value}</div>{caption&&<div className="mt-1 text-xs text-slate-500">{caption}</div>}</Card>}
export function Divider(){return <div className="my-4 h-px bg-slate-200/70 dark:bg-slate-700/70"/>}
export function SectionTitle({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className="mb-5 flex items-end justify-between gap-4"><div><h2 className="text-lg font-black">{title}</h2>{description&&<p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{action}</div>}
